### ISSUE TITLE
Extract protobuf spec into own repository

### ISSUE THREAD

**Issue by sillydan1** [sillydan1/graphedit#36]
It's a bit too annoying with the copy-paste mess... Having the lsp.proto in a seperate repository would make it easier to synchronize versions.

Maybe also consider if there are someone who've made a protobuf package manager - this could also be your time to shine 🌞 

Nevermind, this [buffrs](https://github.com/helsing-ai/buffrs) looks like the way to go (once they have the buffrs registry up and running)

**Comment by sillydan1** [comment]
I can't keep waiting for buffrs central repository to be done. I should just host the docker container on the gtz.dk servers for now.

**Comment by sillydan1** [comment]
It seems the registry container is still very much a [work in progress](https://github.com/helsing-ai/buffrs/pull/173). We might have to do something custom and temporary in the meanwhile.

**Comment by sillydan1** [comment]
Closing with the creation of https://github.com/sillydan1/graphedit-protobuf

**Comment by mara-schulke** [comment]
Hi @sillydan1,

we pivoted our efforts in buffrs towards supporting OCI registries over a custom registry.

See https://github.com/helsing-ai/buffrs/issues/229 for tracking

**Comment by sillydan1** [comment]
Hi @mara-schulke!

That looks very interesting! I will make sure to keep an eye out for that!
